[deps]
Airtable = "96f7d883-6668-4fbe-bb01-b60427b16035"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BiobakeryUtils = "fa5322f5-bd84-5069-834a-abf3230fb8f8"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Microbiome = "3bd8f0ae-a0f2-5238-a5af-e1b399a4940c"
QuickMenus = "2230646a-bae9-43e2-a071-fff97e6a4342"
