name = "VKCComputing"
uuid = "329a1d7f-a79a-43b8-8671-feb503123859"
version = "0.3.0"

[deps]
Airtable = "96f7d883-6668-4fbe-bb01-b60427b16035"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BiobakeryUtils = "fa5322f5-bd84-5069-834a-abf3230fb8f8"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
ArgParse = "1.2.0"
CSV = "0.10.11"
CairoMakie = "0.13.1"
GLM = "1.9.0"
